service:
  name: Template

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  region: us-west-2
  memorySize: 128
  timeout: 3

custom:
  # exclude the aws-sdk to reduce bundle size
  webpackIncludeModules:
    forceExclude:
      - aws-sdk

functions:
  pokeClassDetect:
    #role: //TODO
    handler: handler.handler
    events:
      - http:
          method: get
          path: hello
