matrix:
  include:
  - language: python
    python: 3.6
    env: PROJECT=getcertificate
    before_script: 
    - nvm install 10
    - npm install -g serverless
    - yarn
    - pip install pipenv
  - language: nodejs
    nodejs: 10
    env: PROJECT=classdetector
    before_script: npm install -g serverless
  - language: nodejs
    nodejs: 10
    env: PROJECT=personalsite
    before_script: npm install -g serverless
cache: yarn
script:
- cd $PROJECT && pwd 
- serverless package --stage=prod
branches:
  only:
  - master
  - /^greenkeeper.*$/