matrix:
  include:
  - language: python
    python: 3.7
    env: PROJECT=getcertificate
    before_script: 
    - nvm install 10
    - npm install -g serverless
    - yarn
    - pip install pipenv
  - language: node_js
    nodejs: 10
    env: PROJECT=classdetector
    before_script: npm install -g serverless
  - language: node_js
    nodejs: 10
    env: PROJECT=personalsite
    before_script: npm install -g serverless
dist: bionic
cache: yarn
script:
- cd $PROJECT && pwd 
- serverless package --stage=prod
branches:
  only:
  - master
  - /^greenkeeper.*$/
deploy:
  provider: script
  script: if ../.travis/project-has-new-commits.sh $TRAVIS_COMMIT_RANGE $PROJECT; then serverless deploy --stage=prod; else echo "NO CHANGES SINCE LAST COMMIT"; fi
