language: node_js
node_js:
  - "10"
cache: yarn
env:
  - PROJECT=classdetector
  - PROJECT=getcertificate
  - PROJECT=personalsite
before_script: 
 - npm install -g serverless
 - pip install pipenv
script:
  - cd $PROJECT && pwd 
  - serverless package --stage=prod
branches:
  only:
    - master
    - /^greenkeeper.*$/