service:
  name: PersonalAPI

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2
  memorySize: 128
  timeout: 3

  # TODO: API key base authorization and rate limiting

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
